<?xml version="1.0"?>
<!DOCTYPE student [
    <!ELEMENT student (name, rollno, course)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT rollno (#PCDATA)>
    <!ELEMENT course (#PCDATA)>
]>
<student>
    <name>Satty</name>
    <rollno>101</rollno>
    <course>BTech</course>
</student>
<student>
    <name>Rahul</name>
    <rollno>102</rollno>
    <course>BArch</course>
</student>